# Generated by Django 3.2.8 on 2021-11-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('hospital_ward', models.CharField(max_length=50)),
                ('expertise', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('hospital_ward', models.CharField(max_length=50)),
                ('date_of_admission', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
