# Generated by Django 3.2.8 on 2021-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.IntegerField()),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.IntegerField()),
                ('apartment_number', models.IntegerField(blank=True)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['postal_code'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('hospital_ward', models.CharField(max_length=50)),
                ('date_of_admission', models.DateField()),
            ],
            options={
                'ordering': ['patient_id'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('visit_type', models.CharField(max_length=70)),
                ('specialization_required', models.CharField(max_length=40)),
                ('hospital_address', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'ordering': ['visit_id'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('hospital_ward', models.CharField(max_length=50)),
                ('specializations', models.ManyToManyField(to='API.Specialization')),
            ],
            options={
                'ordering': ['doctor_id'],
            },
        ),
    ]
