# Generated by Django 3.2.8 on 2021-11-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_address_apartment_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
