# Generated by Django 3.2.8 on 2021-11-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_delete_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('leading_doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.doctor')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.address')),
                ('required_specialization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.specialization')),
                ('visited_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.patient')),
            ],
            options={
                'ordering': ['visit_id'],
            },
        ),
    ]
